baseURL = "/"
title = "Frenchie"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral-master"

[params]
fancyTitle = "Finding Home: The Journey to True Freedom" # title for frontpage, may include image
copyright = "Spectral"
description = 'a journey filled with self-discovery, personal growth,<br />and ultimately,<br />the realization of true freedom'
#startbuttonText = "Posts"
#startbuttonLink = "/posts"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]
ShowDatesOnPosts = false

[[params.assets]]
favicon = "/favicon.png"

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = false
title = 'Arcu aliquet vel lobortis ata nisl<br />eget augue amet aliquet nisl cep donec'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.one.icon]]
icon = "fa-diamond"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-heart-o"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-code"
style = "3"
label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "/static/frenchie-previews.png"
title = 'The Duality of Life&#x27; Pursuits'
body = 'On this marvelous lantern rite, we pray that the fallen heros may be guided home.'

[[params.two.section]]
img = "/static/frenchie-lookup.png"
title = 'Striving for Success and Enjoyment'
body = 'Every single wish, no matter how small, is worth seeing to fruition.'

[[params.two.section]]
img = "/static/frenchie-balls.png"
title = 'Balancing Rest and Fun'
body = 'We will finally reunite with those we long for on a dreamlike night.'

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""

